# Generated by Django 3.1.7 on 2021-06-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210601_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='housename',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='statename',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateof', to='api.state'),
        ),
    ]
