# Generated by Django 3.1.7 on 2021-06-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210601_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='housename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='statename',
            new_name='name',
        ),
    ]
